export const RECRUITMENT_STATUSES = [
  "LEAD", "PRE_CADASTRO", "TRIAGEM", "CONVERSA_PENDENTE", "ENTREVISTA",
  "REFERENCIA", "PRE_APROVADA", "DOCUMENTACAO", "ONBOARDING",
  "TESTE_OPERACIONAL", "EM_VALIDACAO", "ATIVA", "PREFERENCIAL",
  "PRECISA_DE_AJUDA", "LIGACAO_SOLICITADA", "BASE_FUTURA",
  "AGUARDANDO_COMPLEMENTACAO", "REPROVADA", "DESISTIU", "PAUSADA", "SUSPENSA",
] as const;

export type RecruitmentStatus = (typeof RECRUITMENT_STATUSES)[number];
