"use server";

import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import type { LeadOrigin } from "@prisma/client";
import { auth } from "@/infrastructure/auth/auth";
import { prisma } from "@/infrastructure/db/prisma-client";
import { addLeadNote } from "@/application/recruitment/lead-notes.usecase";
import { createLeadUseCase } from "@/application/recruitment/create-lead.usecase";
import { transitionLeadStatusUseCase } from "@/application/recruitment/transition-lead-status.usecase";
import { addAssessment, addProfessionalReference, completeInterview, startInterview, verifyReference } from "@/application/recruitment/interviews-references.usecase";
import type { AssessmentLevel, InterviewResult, ReferenceStatus, WouldHireAgain } from "@prisma/client";
import type { RecruitmentStatus } from "@/domain/recruitment/recruitment-status";

async function currentActor(): Promise<string | null> { const session = await auth.api.getSession({ headers: await headers() }); const email = session?.user.email; if (!email) return null; const user = await prisma.user.findFirst({ where: { email, role: "ADMIN" } }); return user?.email ?? null; }
const result = (ok: boolean, error?: string) => (error === undefined ? { ok } : { ok, error });
export async function moveLeadAction(input: { leadId: string; targetStatus: RecruitmentStatus; overrideReason?: string }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); const moved = await transitionLeadStatusUseCase(prisma, { ...input, actor, ...(input.overrideReason?.trim() ? { override: { reason: input.overrideReason.trim() } } : {}) }); revalidatePath("/admin/recruitment"); return moved.ok ? result(true) : result(false, moved.error.message); }
export async function addQuickNoteAction(input: { leadId: string; content: string }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); const note = await addLeadNote(prisma, { ...input, author: actor }); revalidatePath("/admin/recruitment"); return note.ok ? result(true) : result(false, note.error.message); }
export async function createLeadAction(input: { origin: LeadOrigin; fullName?: string; phoneE164?: string; neighborhood?: string }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); const lead = await createLeadUseCase(prisma, { ...input, actor }); revalidatePath("/admin/recruitment"); return lead.ok ? result(true) : result(false, lead.error.message); }
export async function startInterviewAction(leadId: string) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); try { await startInterview(prisma, { leadId, interviewer: actor }); revalidatePath(`/admin/recruitment/${leadId}`); return result(true); } catch (error) { return result(false, error instanceof Error ? error.message : "Não foi possível iniciar entrevista."); } }
export async function completeInterviewAction(input: { interviewId: string; result: InterviewResult; notes?: string }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); try { const interview = await completeInterview(prisma, { ...input, interviewer: actor }); revalidatePath(`/admin/recruitment/${interview.leadId}`); return result(true); } catch (error) { return result(false, error instanceof Error ? error.message : "Não foi possível concluir entrevista."); } }
export async function addReferenceAction(input: { leadId: string; name: string; phoneE164?: string; relationship?: string }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); try { await addProfessionalReference(prisma, { ...input, author: actor }); revalidatePath(`/admin/recruitment/${input.leadId}`); return result(true); } catch (error) { return result(false, error instanceof Error ? error.message : "Não foi possível adicionar referência."); } }
export async function verifyReferenceAction(input: { referenceId: string; leadId: string; status: ReferenceStatus; comment?: string; wouldHireAgain?: WouldHireAgain }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); try { await verifyReference(prisma, { ...input, verifiedBy: actor }); revalidatePath(`/admin/recruitment/${input.leadId}`); return result(true); } catch (error) { return result(false, error instanceof Error ? error.message : "Não foi possível verificar referência."); } }
export async function addAssessmentAction(input: { leadId: string; notes?: string; experience?: AssessmentLevel; reliability?: AssessmentLevel; communication?: AssessmentLevel; availability?: AssessmentLevel }) { const actor = await currentActor(); if (!actor) return result(false, "Sessão expirada."); try { await addAssessment(prisma, { ...input, author: actor }); revalidatePath(`/admin/recruitment/${input.leadId}`); return result(true); } catch (error) { return result(false, error instanceof Error ? error.message : "Não foi possível registrar avaliação."); } }
