import type { AssessmentLevel, InterviewResult, PrismaClient, ReferenceStatus, WouldHireAgain } from "@prisma/client";
import type { RecruitmentStatus } from "../../domain/recruitment/recruitment-status";
import { DomainError } from "../../domain/shared/domain-error";
import { recordAuditLog } from "../audit/record-audit-log.usecase";
import { transitionLeadStatusInTransaction } from "./transition-lead-status.usecase";

const resultStatus: Record<InterviewResult, RecruitmentStatus> = { REFERENCIA: "REFERENCIA", AGUARDANDO_COMPLEMENTACAO: "AGUARDANDO_COMPLEMENTACAO", BASE_FUTURA: "BASE_FUTURA", REPROVADA: "REPROVADA" };
export async function startInterview(prisma: PrismaClient, input: { leadId: string; interviewer: string }) { return prisma.$transaction(async (tx) => { const lead = await tx.recruitmentLead.findUnique({ where: { id: input.leadId } }); if (!lead) throw new DomainError("Lead não encontrado", "LEAD_NOT_FOUND"); if (lead.status !== "CONVERSA_PENDENTE") throw new DomainError("Entrevista exige conversa pendente", "INTERVIEW_NOT_ALLOWED"); const transition = await transitionLeadStatusInTransaction(tx, { leadId: lead.id, targetStatus: "ENTREVISTA", actor: input.interviewer }); if (!transition.ok) throw transition.error; const interview = await tx.leadInterview.create({ data: input }); await tx.leadEvent.create({ data: { leadId: input.leadId, type: "INTERVIEW_STARTED", description: "Entrevista iniciada", actor: input.interviewer } }); await recordAuditLog(tx, { actor: input.interviewer, action: "LEAD_INTERVIEW_STARTED", entityType: "LeadInterview", entityId: interview.id }); return interview; }); }
export async function completeInterview(prisma: PrismaClient, input: { interviewId: string; interviewer: string; notes?: string; result: InterviewResult }) { return prisma.$transaction(async (tx) => { const current = await tx.leadInterview.findUnique({ where: { id: input.interviewId }, include: { lead: true } }); if (!current) throw new DomainError("Entrevista não encontrada", "INTERVIEW_NOT_FOUND"); if (current.endedAt) throw new DomainError("Entrevista já concluída", "INTERVIEW_ALREADY_COMPLETED"); const changed = await tx.leadInterview.updateMany({ where: { id: current.id, endedAt: null }, data: { endedAt: new Date(), result: input.result, ...(input.notes !== undefined ? { notes: input.notes } : {}) } }); if (!changed.count) throw new DomainError("Entrevista já concluída", "INTERVIEW_ALREADY_COMPLETED"); const transition = await transitionLeadStatusInTransaction(tx, { leadId: current.leadId, targetStatus: resultStatus[input.result], actor: input.interviewer }); if (!transition.ok) throw transition.error; const interview = await tx.leadInterview.findUniqueOrThrow({ where: { id: current.id } }); await tx.leadEvent.create({ data: { leadId: interview.leadId, type: "INTERVIEW_COMPLETED", description: "Entrevista concluída", actor: input.interviewer } }); await recordAuditLog(tx, { actor: input.interviewer, action: "LEAD_INTERVIEW_COMPLETED", entityType: "LeadInterview", entityId: interview.id }); return interview; }); }
export async function addAssessment(prisma: PrismaClient, input: { leadId: string; author: string; experience?: AssessmentLevel; reliability?: AssessmentLevel; communication?: AssessmentLevel; availability?: AssessmentLevel; notes?: string }) { return prisma.$transaction(async (tx) => { const assessment = await tx.leadAssessment.create({ data: input }); await recordAuditLog(tx, { actor: input.author, action: "LEAD_ASSESSMENT_RECORDED", entityType: "LeadAssessment", entityId: assessment.id }); return assessment; }); }
export async function addProfessionalReference(prisma: PrismaClient, input: { leadId: string; author: string; name: string; phoneE164?: string; relationship?: string }) { return prisma.$transaction(async (tx) => { const reference = await tx.professionalReference.create({ data: { leadId: input.leadId, name: input.name, ...(input.phoneE164 ? { phoneE164: input.phoneE164 } : {}), ...(input.relationship ? { relationship: input.relationship } : {}) } }); await tx.leadEvent.create({ data: { leadId: input.leadId, type: "REFERENCE_ADDED", description: "Referência adicionada", actor: input.author } }); await recordAuditLog(tx, { actor: input.author, action: "PROFESSIONAL_REFERENCE_ADDED", entityType: "ProfessionalReference", entityId: reference.id }); return reference; }); }
export async function verifyReference(prisma: PrismaClient, input: { referenceId: string; verifiedBy: string; status: ReferenceStatus; comment?: string; wouldHireAgain?: WouldHireAgain }) { return prisma.$transaction(async (tx) => { const reference = await tx.professionalReference.update({ where: { id: input.referenceId }, data: { status: input.status } }); const verification = await tx.referenceVerification.create({ data: { referenceId: reference.id, verifiedBy: input.verifiedBy, ...(input.comment !== undefined ? { comment: input.comment } : {}), ...(input.wouldHireAgain !== undefined ? { wouldHireAgain: input.wouldHireAgain } : {}) } }); await tx.leadEvent.create({ data: { leadId: reference.leadId, type: "REFERENCE_VERIFIED", description: "Referência verificada", actor: input.verifiedBy } }); await recordAuditLog(tx, { actor: input.verifiedBy, action: "PROFESSIONAL_REFERENCE_VERIFIED", entityType: "ProfessionalReference", entityId: reference.id }); return verification; }); }
