import { Prisma, type OperationalTestResult, type PrismaClient } from "@prisma/client";
import { DomainError } from "../../domain/shared/domain-error";
import { recordAuditLog } from "../audit/record-audit-log.usecase";
import { transitionLeadStatusInTransaction } from "./transition-lead-status.usecase";

async function requireAdmin(prisma: PrismaClient, actor: string): Promise<void> { const admin = await prisma.user.findFirst({ where: { email: actor, role: "ADMIN" } }); if (!admin) throw new DomainError("Acesso administrativo necessário", "ADMIN_REQUIRED"); }

export async function completeOnboardingContent(prisma: PrismaClient, input: { leadId: string; contentId: string; channel: string; actor: string }) { await requireAdmin(prisma, input.actor); return prisma.$transaction(async (tx) => { const lead = await tx.recruitmentLead.findUnique({ where: { id: input.leadId }, select: { status: true } }); if (!lead || lead.status !== "ONBOARDING") throw new DomainError("Onboarding não está disponível nesta etapa", "ONBOARDING_NOT_ALLOWED"); const content = await tx.onboardingContent.findUnique({ where: { id: input.contentId } }); if (!content?.isActive) throw new DomainError("Conteúdo de onboarding inválido", "ONBOARDING_CONTENT_NOT_FOUND"); const progress = await tx.leadOnboardingProgress.upsert({ where: { leadId_contentId: { leadId: input.leadId, contentId: input.contentId } }, create: input, update: {} }); await tx.leadEvent.create({ data: { leadId: input.leadId, type: "ONBOARDING_CONTENT_COMPLETED", description: `Onboarding concluído: ${content.title}`, actor: input.actor } }); return progress; }); }
export async function startOperationalTest(prisma: PrismaClient, input: { leadId: string; actor: string }) { await requireAdmin(prisma, input.actor); return prisma.$transaction(async (tx) => { const lead = await tx.recruitmentLead.findUnique({ where: { id: input.leadId } }); if (!lead || lead.status !== "TESTE_OPERACIONAL") throw new DomainError("Teste operacional não permitido", "OPERATIONAL_TEST_NOT_ALLOWED"); const active = await tx.onboardingContent.count({ where: { isActive: true } }); const complete = await tx.leadOnboardingProgress.count({ where: { leadId: input.leadId, content: { isActive: true } } }); if (!active || complete !== active) throw new DomainError("Onboarding ainda não concluído", "ONBOARDING_NOT_COMPLETED"); const test = await tx.operationalTest.create({ data: { leadId: input.leadId, activeKey: input.leadId } }); await tx.operationalTestEvent.create({ data: { testId: test.id, type: "STARTED", actor: input.actor } }); return test; }); }
export async function recordOperationalTestEvent(prisma: PrismaClient, input: { testId: string; type: "ACCEPTED" | "EN_ROUTE" | "ARRIVED" | "COMPLETED" | "HELP"; actor: string }) { await requireAdmin(prisma, input.actor); try { return await prisma.$transaction(async (tx) => { const test = await tx.operationalTest.findUnique({ where: { id: input.testId }, include: { events: { orderBy: { createdAt: "asc" } } } }); if (!test || test.result) throw new DomainError("Teste operacional indisponível", "OPERATIONAL_TEST_NOT_ACTIVE"); const previous = test.events.at(-1)?.type; const allowed: Record<string, string | undefined> = { STARTED: "ACCEPTED", ACCEPTED: "EN_ROUTE", EN_ROUTE: "ARRIVED", ARRIVED: "COMPLETED" }; if (input.type !== "HELP" && allowed[previous ?? ""] !== input.type) throw new DomainError("Comando do teste fora de sequência", "OPERATIONAL_TEST_INVALID_SEQUENCE"); if (input.type === "HELP") await tx.operationalTest.update({ where: { id: test.id }, data: { supportUsed: true } }); return tx.operationalTestEvent.create({ data: input }); }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new DomainError("Etapa do teste já foi registrada", "OPERATIONAL_TEST_EVENT_DUPLICATE"); throw error; } }
export async function decideOperationalTest(prisma: PrismaClient, input: { testId: string; result: OperationalTestResult; actor: string }) { await requireAdmin(prisma, input.actor); return prisma.$transaction(async (tx) => { const test = await tx.operationalTest.findUnique({ where: { id: input.testId }, include: { events: { orderBy: { createdAt: "asc" } } } }); if (!test || test.result) throw new DomainError("Teste operacional já decidido", "OPERATIONAL_TEST_ALREADY_DECIDED"); const completed = test.events.some((event) => event.type === "COMPLETED"); if (input.result !== "FAILED" && !completed) throw new DomainError("Conclua a sequência do teste antes de aprová-lo", "OPERATIONAL_TEST_NOT_COMPLETED"); if (input.result === "PASSED_WITH_SUPPORT" && !test.supportUsed) throw new DomainError("Registre o uso de suporte antes de aprovar com suporte", "OPERATIONAL_TEST_SUPPORT_NOT_RECORDED"); const updated = await tx.operationalTest.update({ where: { id: test.id }, data: { result: input.result, decidedBy: input.actor, decidedAt: new Date(), activeKey: null } }); const targetStatus = input.result === "FAILED" ? "AGUARDANDO_COMPLEMENTACAO" : "EM_VALIDACAO"; const transition = await transitionLeadStatusInTransaction(tx, { leadId: test.leadId, targetStatus, actor: input.actor, ...(input.result === "FAILED" ? { reason: "Teste operacional reprovado; requer complementação ou novo teste" } : {}) }); if (!transition.ok) throw transition.error; if (input.result === "FAILED") await tx.recruitmentLead.update({ where: { id: test.leadId }, data: { nextAction: "Revisar falha do teste operacional", nextActionAt: new Date() } }); await tx.leadEvent.create({ data: { leadId: test.leadId, type: "OPERATIONAL_TEST_DECIDED", description: `Teste operacional: ${input.result}`, actor: input.actor } }); await recordAuditLog(tx, { actor: input.actor, action: "OPERATIONAL_TEST_DECIDED", entityType: "OperationalTest", entityId: test.id }); return updated; }); }
