import type { PrismaClient } from "@prisma/client";
import { env } from "../../env";
import { textPayload } from "../../domain/messaging/message";
import { DomainError } from "../../domain/shared/domain-error";
import { recordAuditLog } from "../audit/record-audit-log.usecase";
import { enqueueOutboundMessage } from "../messaging/enqueue-outbound-message.usecase";
import { transitionLeadStatusInTransaction } from "./transition-lead-status.usecase";

async function requireAdmin(prisma: PrismaClient, actor: string): Promise<void> { const user = await prisma.user.findFirst({ where: { email: actor, role: "ADMIN" } }); if (!user) throw new DomainError("Acesso administrativo necessário", "ADMIN_REQUIRED"); }
export async function recordValidationService(prisma: PrismaClient, input: { leadId: string; externalServiceId: string; actor: string; wasOnTime?: boolean; rating?: number; hadIssue?: boolean; wouldHireAgain?: "YES" | "NO" | "UNSURE"; notes?: string }) { await requireAdmin(prisma, input.actor); const hadIssue = input.hadIssue; if (hadIssue === undefined) throw new DomainError("Informe se houve ocorrência no serviço", "VALIDATION_ISSUE_REQUIRED"); if (input.rating !== undefined && (input.rating < 1 || input.rating > 5)) throw new DomainError("Avaliação inválida", "INVALID_SERVICE_RATING"); return prisma.$transaction(async (tx) => { const lead = await tx.recruitmentLead.findUnique({ where: { id: input.leadId } }); if (!lead || lead.status !== "EM_VALIDACAO") throw new DomainError("Lead não está em validação", "LEAD_NOT_VALIDATING"); const existing = await tx.validationServiceRecord.findUnique({ where: { externalServiceId: input.externalServiceId } }); const service = await tx.validationServiceRecord.upsert({ where: { externalServiceId: input.externalServiceId }, create: { leadId: input.leadId, externalServiceId: input.externalServiceId, ...(input.wasOnTime !== undefined ? { wasOnTime: input.wasOnTime } : {}), ...(input.rating !== undefined ? { rating: input.rating } : {}), hadIssue, ...(input.wouldHireAgain !== undefined ? { wouldHireAgain: input.wouldHireAgain } : {}), ...(input.notes !== undefined ? { notes: input.notes } : {}) }, update: {} }); if (service.leadId !== input.leadId) throw new DomainError("Serviço já vinculado a outro lead", "VALIDATION_SERVICE_CONFLICT"); if (!existing) await tx.leadEvent.create({ data: { leadId: input.leadId, type: "VALIDATION_SERVICE_RECORDED", description: "Serviço de validação registrado", actor: input.actor } }); return service; }); }
export async function decideValidation(prisma: PrismaClient, input: { leadId: string; decision: "ATIVA" | "PAUSADA" | "REPROVADA" | "PREFERENCIAL"; reason?: string; actor: string }) { await requireAdmin(prisma, input.actor); return prisma.$transaction(async (tx) => { const lead = await tx.recruitmentLead.findUnique({ where: { id: input.leadId }, include: { conversation: { select: { provider: true } } } }); if (!lead) throw new DomainError("Lead não encontrado", "LEAD_NOT_FOUND"); const policy = await tx.validationPolicy.findFirst({ where: { isActive: true }, orderBy: { createdAt: "desc" } }); if (!policy || policy.requiredServices < 1) throw new DomainError("Política de validação inválida", "VALIDATION_POLICY_NOT_CONFIGURED"); const records = await tx.validationServiceRecord.findMany({ where: { leadId: lead.id } }); const eligible = records.length >= policy.requiredServices && records.every((record) => record.hadIssue === false); const reason = input.reason?.trim(); if (((input.decision === "ATIVA" || input.decision === "PREFERENCIAL") && !eligible) || ["PAUSADA", "REPROVADA"].includes(input.decision)) { if (!reason) throw new DomainError("Decisão exige motivo", "VALIDATION_DECISION_REASON_REQUIRED"); } const transition = await transitionLeadStatusInTransaction(tx, { leadId: lead.id, targetStatus: input.decision, actor: input.actor, ...(reason ? { reason } : {}) }); if (!transition.ok) throw transition.error; const decision = await tx.validationDecision.create({ data: { leadId: lead.id, decision: input.decision, eligible, ...(reason ? { reason } : {}), decidedBy: input.actor } }); await recordAuditLog(tx, { actor: input.actor, action: "VALIDATION_DECIDED", entityType: "ValidationDecision", entityId: decision.id, metadata: { eligible, decision: input.decision } }); if ((input.decision === "ATIVA" || input.decision === "PREFERENCIAL") && lead.phoneE164) { const congratsText = input.decision === "PREFERENCIAL" ? `Parabéns${lead.fullName ? `, ${lead.fullName}` : ""}! 🎉 Você é agora uma profissional preferencial da AllSet. Em breve entraremos em contato com os próximos passos.` : `Parabéns${lead.fullName ? `, ${lead.fullName}` : ""}! 🎉 Você foi ativada como profissional da AllSet. Em breve entraremos em contato com os próximos passos.`; await enqueueOutboundMessage(tx, { provider: lead.conversation?.provider ?? env.MESSAGING_DEFAULT_PROVIDER, recipient: lead.phoneE164, payload: textPayload(congratsText), idempotencyKey: `validation:${decision.id}:welcome`, correlationId: lead.id, actor: "system:validation" }); } return decision; }); }
